## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -261.47
accel_x_max: 271.73
accel_y_min: -274.29
accel_y_max: 280.88
accel_z_min: -275.76
accel_z_max: 269.41

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.02
gyro_average_offset_y: -0.01
gyro_average_offset_z: -0.01
